project:
  type: website

website:
  title: "The Data Shrink"
  image: images/tds-logo-150px.png
  favicon: images/tds-favicon.png
  twitter-card:
    site: "@TheDataShrink"
  open-graph: true
  site-url: https://www.thedatashrink.com/
  repo-url: https://github.com/TheDataShrink/TheDataShrink.github.io
  repo-actions: [edit, issue]
  navbar:
    toggle-position: right
    background: "#f0eeeb"
    logo: images/tds-logo-150px.png
    logo-alt: "The Data Shrink brand"
    title: false
    collapse-below: lg
    right:
      - text: "About"
        menu:
          - text: "Why we shrink"
            href: about/why-we-shrink.qmd
          - text: "Team"
            href: about/team.qmd
          - text: "Partnerships"
            href: about/partnerships.qmd
          - text: "For Contributors"
            href: about/for-contributors.qmd
      - text: "Shrink Tank"
        href: shrinktank/index.qmd
      - text: "Use Cases"
        menu:
          - text: "Project task"
            href: use-cases/index.qmd
          - text: "Introduction"
            href: about/01-introduction.qmd
          - text: "Data Reception"
            href: use-cases/02-data-reception.qmd
          - text: "Data Preparation"
            href: use-cases/03-data-preparation.qmd
          - text: "Data Evaluation"
            href: use-cases/05-evaluation.qmd 
          - text: "Implementation"
            href: use-cases/06-implementation.qmd
          - text: "User Guides"
            href: use-cases/appendix-b.qmd
          - text: "Technical Documentation"
            href: use-cases/appendix-a.qmd
          - text: "References and Glossary"
            href: use-cases/appendix-c.qmd
      - text: "Viewpoints"
        href: viewpoints/index.qmd
      - text: "Courses"
        href: courses/index.qmd
      - text: "Contact"
        href: contact.qmd

  page-footer:
    left: "Copyright © 2024 The Data Shrink. All rights reserved."
    right:
      - icon: github
        href: https://github.com/TheDataShrink
      - icon: twitter
        href: https://twitter.com/TheDataShrink
      - icon: linkedin
        href: https://www.linkedin.com/company/the-data-shrink

format:
  html:
    theme: [cyborg, tds.scss]
    css: tds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute:
  freeze: auto