project:
  type: website

website:
  # --- CHANGED: Updated title and description for better OG data ---
  title: "Dr. Shrink | AI-Powered Music Therapy"
  description: "Experience a revolutionary journey turning your feelings into personalized, therapeutic songs. Start your healing process with Dr. Shrink."
  image: images/tds-logo-150px.png
  favicon: images/tds-favicon.png
  twitter-card:
    site: "@TheDataShrink"
  open-graph: true
  site-url: https://www.thedatashrink.com/
  repo-url: https://github.com/TheDataShrink/TheDataShrink.github.io
  repo-actions: [edit, issue]
  navbar:
    toggle-position: right
    background: "#27ae60"  # Intense healing green
    logo: images/tds-logo-150px.png
    logo-alt: "Music-Soul-Love"
    title: false
    collapse-below: lg
    right:
    - text: "How It Works"
      href: process/index.qmd
    - text: "Testimonials"
      href: testimonials/index.qmd
    - text: "Song Gallery"
      href: gallery/index.qmd
    - text: "Science"
      href: science/index.qmd
    - text: "Resources"
      href: resources/index.qmd

  page-footer:
    left: "Copyright © 2025 The Data Shrink. All rights reserved."
    right:
      - icon: instagram
        href: https://instagram.com/thedatashrink
      - icon: spotify
        href: https://open.spotify.com/user/thedatashrink
      - icon: twitter
        href: https://twitter.com/TheDataShrink
      - icon: youtube
        href: https://youtube.com/@TheDataShrink

format:
  html:
    theme: [default, tds-therapy.scss]
    css: 
      - tds-therapy.css
    toc: false

execute:
  freeze: auto