name: Quarto Publish

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: rstudio/actions/setup-r@v2
        with:
          r-version: '4.3'

      - name: Set up R library path
        run: |
          mkdir -p ~/R/library
          echo 'R_LIBS_USER="~/R/library"' > ~/.Renviron

      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Install renv and restore dependencies
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Clean _site directory
        run: rm -rf _site || true

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Commit and Push Changes (Optional)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Automated render and deploy by GitHub Actions" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
