on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # with:
        #   To install LaTeX to build PDF book 
        #   tinytex: true 
        #   uncomment below and fill to pin a version
        #   version: pre-release
          
      # - name: Setup Python
      #   uses: actions/setup-python@v4.1.0
            
      # add software dependencies here
      
      # - name: Install python dependencies
      #   run: |
      #     python -m pip install jupyter
      #     python -m pip install numpy
      #     python -m pip install matplotlib

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Automated render and deploy by GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
